### ISSUE TITLE
Gebruiker kan festival details bekijken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#100]
### Must have
- User kan per festival een korte indruk krijgen van het festival dmv beeld, geluid en text. Denk aan link naar de website, foto’s, text omschrijving en audio samples van alle artiesten die optreden
- User kan per festival alle artiesten bekijken die er optreden
- User kan per festival het programma bekijken
- User kan keuze voor een festival delen
- Naam
- Locatie
- Datum/tijd
- Omschrijving
- Fotos
- Artiesten CTA
- Aangemelde vrienden
- Nieuws / Berichten van organisator
- Aanmelden CTA
- Timetable bekijken / zelf samen stellen

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-2](https://cloud.githubusercontent.com/assets/2156865/12547608/9681d82c-c351-11e5-84cb-a9e56c66338c.jpg)

**Comment by vincentlindeboom** [comment]
helemaal mee eens. Ik vraag me bij de description nog af of we die niet moeten vervangen door een gegenereerde "omschrijving" bv alleen bestaande uit genres. Elke beschrijving is subjectief en voegt in general niet heel veel toe m.i. Een gegenereerde word-cloud van bv genres zou mij meer vertellen.. #nietvoornu

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom hebben jullie concrete info die jullie vooraf op het dashboard van een festival willen tonen?

**Comment by vincentlindeboom** [comment]
artiesten, push (voor alle mutaties aangaande programmering) en als we ze weten ook je vrienden die gaan

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![festival detail vooraf copy](https://cloud.githubusercontent.com/assets/2156865/12670081/ce858752-c665-11e5-91b9-9f9b7eeb72c6.png)
