### ISSUE TITLE
Gebruiker kan artiest detail view bekijken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#101]
### Must have
- User kan per artiest een korte omschrijving bekijken (foto, text, audio samples)
- CTA om optreden per festival toe te voegen aan persoonlijk programma

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-1](https://cloud.githubusercontent.com/assets/2156865/12547501/27075f6c-c351-11e5-9892-5992fcde1067.jpg)

**Comment by vincentlindeboom** [comment]
- ook op andree festivals (hoeft van mij niet - meer optioneel, maar zoals besproken niet helemaal op zijn plek hier denk ik. iig niet via dee route)

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![artiest](https://cloud.githubusercontent.com/assets/2156865/12670042/6f3db24c-c665-11e5-9b73-f0d61a51ccb2.png)
