### ISSUE TITLE
Gebruiker kan festival line-up bekijken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#102]
### Must have
- User ziet lijst met artiesten automatisch gesorteerd op Spotify/LastFM data
- Gebruiker ziet wanneer vrienden naar een artiest gaan
- Gebruiker kan artiesten direct toevoegen aan persoonlijk programma
- Gebruiker kan per artiest een detail view bekijken
- Gebruiker kan artiesten lijst sorteren op alfabetische volgorde
- Sorteren op tijd

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload](https://cloud.githubusercontent.com/assets/2156865/12547485/15a304e2-c351-11e5-94c2-4e3090067840.jpg)

**Comment by vincentlindeboom** [comment]
zodra de timetable bekend is wil je ook kunnen sorteren op tijd-schema denk ik.

**Comment by Martijn-Vermeulen** [comment]
@vincentlindeboom true

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![lineup](https://cloud.githubusercontent.com/assets/2156865/12670025/57a84840-c665-11e5-96e1-e5cc735f5215.png)
