### ISSUE TITLE
Gebruiker heeft een muziek profiel

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#103]
Muziek profiel bevat informatie over de artiesten voorkeur van een gebruiker op basis van verzamelde data. Deze data kan gebruikt worden om festival line-ups persoonlijker te maken.

## Requirements
- Artiesten die de gebruiker toevoegt aan persoonlijk programma hebben invloed op muziek profiel
- Acties an vrienden hebben invloed op muziek profiel
- Op basis van artiesten keuzes nagaan welke artiesten daar nog meer op lijken op aanbevelingen te doen
- Optie voor data importeren van Spotify account
- Optie voor data importeren van Lastfm account
- Eventueel binnen de app muziek voorkeur aangeven

**Comment by vincentlindeboom** [comment]
alleen het 2e punt zie ik niet. alle vrienden-activiteit (festivals, artiesten) is nuttige om te gebruiken voor recommendations, maar heeft geen dirrecte invloed op mijn profiel toch?

**Comment by bavaross** [comment]
zie de link ook niet direct

**Comment by bavaross** [comment]
ik zou ook wel graag willen weten hoe dit eruit komt te zien (zie comment vincent over muziekpaspoort)

**Comment by Martijn-Vermeulen** [comment]
Het muziekprofiel gebeurt allemaal in de achtergrond aan de hand van koppelingen met bijvoorbeeld Spotify. Er is geen scherm waar je je eigen 'muziekpaspoort' visueel ziet. Je 'muziekpaspoort' komt naar voren binnen de app aan de hand van aanbevelingen voor optredens op een festival.

**Comment by vincentlindeboom** [comment]
Is je eigen profiel niet een plek waar we ook iets kunnen tonen over jouw "smaak"?
Dat bedoelde ik met muziek-paspoort

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom het is onze visie dat we op de achtergrond zo veel mogelijk data verzamelen en daarmee de smaak van de gebruiker kunnen gebruiken om persoonlijke adviezen uit te kunnen dragen. Het is ons niet helemaal duidelijk hoe een overzicht van deze data binnen de scope van deze app valt? Lijkt ons juist een betere ervaring dat dit allemaal op de achtergrond gebeurt zodat de gebruiker kan focussen op de festival beleving.
