### ISSUE TITLE
Finalise all wireframes

### ISSUE THREAD

**Issue by kevinkalle** [awkward/rewind#104]

**Comment by daniellouwekooijmans** [comment]
### All wireframes

![festival detail na](https://cloud.githubusercontent.com/assets/2156865/12670212/e0994126-c666-11e5-828d-9e7369c265cd.png)
![festival detail tijdens](https://cloud.githubusercontent.com/assets/2156865/12670213/e099c704-c666-11e5-8c80-5b681f199a25.png)
![festivals toevoegen](https://cloud.githubusercontent.com/assets/2156865/12670214/e099e48c-c666-11e5-862d-5c7d00b159db.png)
![suggesties](https://cloud.githubusercontent.com/assets/2156865/12670215/e09a8522-c666-11e5-8fb1-84daf5936346.png)
![programma share](https://cloud.githubusercontent.com/assets/2156865/12670216/e09b0312-c666-11e5-931f-46f96871be9e.png)
![programma](https://cloud.githubusercontent.com/assets/2156865/12670217/e09d74bc-c666-11e5-8f4e-c9d3a5c436d4.png)
![programma copy](https://cloud.githubusercontent.com/assets/2156865/12670218/e0b30bce-c666-11e5-8e5a-60974038936b.png)
![festival detail tijdens vrienden](https://cloud.githubusercontent.com/assets/2156865/12670222/e0b58912-c666-11e5-9c3f-800e0ac477ef.png)
![festival nieuws detail](https://cloud.githubusercontent.com/assets/2156865/12670219/e0b338c4-c666-11e5-8cb8-95ee5e4cf510.png)
![festival nieuws overzicht](https://cloud.githubusercontent.com/assets/2156865/12670221/e0b4905c-c666-11e5-80a6-831b3e9a9e9e.png)
![settings](https://cloud.githubusercontent.com/assets/2156865/12670220/e0b35138-c666-11e5-82ab-120dbd7cb265.png)
![login9](https://cloud.githubusercontent.com/assets/2156865/12670223/e0bcd82a-c666-11e5-8c13-cc08eb1fa28c.png)
![login7](https://cloud.githubusercontent.com/assets/2156865/12670224/e0ca51bc-c666-11e5-86bc-5c9761c85227.png)
![login6](https://cloud.githubusercontent.com/assets/2156865/12670226/e0cac340-c666-11e5-8fce-7b48e2e260eb.png)
![login5](https://cloud.githubusercontent.com/assets/2156865/12670225/e0caac8e-c666-11e5-996d-c01a8438aa60.png)
![login4](https://cloud.githubusercontent.com/assets/2156865/12670227/e0cce1b6-c666-11e5-841f-1246bb44849a.png)
![login3](https://cloud.githubusercontent.com/assets/2156865/12670228/e0ce2b5c-c666-11e5-91b4-6ba394204417.png)
![login2](https://cloud.githubusercontent.com/assets/2156865/12670229/e0d431dc-c666-11e5-981b-707c9e0c1682.png)
![login1](https://cloud.githubusercontent.com/assets/2156865/12670230/e0da955e-c666-11e5-8370-8cb8822daf8f.png)
![festival detail vooraf copy](https://cloud.githubusercontent.com/assets/2156865/12670231/e0db2eba-c666-11e5-9987-37f70d4eb24f.png)
![sort options](https://cloud.githubusercontent.com/assets/2156865/12670234/e0e15b1e-c666-11e5-98e0-e12bd708c580.png)
![artiest](https://cloud.githubusercontent.com/assets/2156865/12670232/e0dd384a-c666-11e5-8ad3-4edeb820fe87.png)
![lineup](https://cloud.githubusercontent.com/assets/2156865/12670233/e0deaf18-c666-11e5-8ff2-e28792ce16e8.png)
![mijnfestivals](https://cloud.githubusercontent.com/assets/2156865/12670235/e0e96e58-c666-11e5-9910-9b9412470bb0.png)
