### ISSUE TITLE
Om dagboek te personaliseren kan gebruiker muziekprofiel aanmaken

### ISSUE THREAD

**Issue by barbarableeker** [awkward/rewind#30]

**Comment by daniellouwekooijmans** [comment]
@kevinkalle wat houd een muziek profiel in?

**Comment by kevinkalle** [comment]
Weet ik niet, vraag voor morgen.

**Comment by kevinkalle** [comment]
"muziekprofiel" staat in description. is eigenlijk de 10 vragen test (los van de festivals). als we dat goed kunnen zie ik toegevoegde waarde; is wel een feature die makkelijk weg zou kunnen. maar nogmaals als we het goed kunnen wordt dat bijna een usp.

**Comment by daniellouwekooijmans** [comment]
@kevinkalle welke description? Belangrijk om te weten tijdens welke stap in het proces we dit introduceren. Wellicht tijdens het aanmaken van een profiel.

**Comment by kevinkalle** [comment]
Weet ik niet, even vragen vanmiddag.
