### ISSUE TITLE
Om na te genieten kan gebruiker zijn foto's terugzien in de context van het festival

### ISSUE THREAD

**Issue by barbarableeker** [awkward/rewind#60]

**Comment by daniellouwekooijmans** [comment]
@kevinkalle wat is de context van het festival? Niet helemaal duidelijk hoe ik dit moet intepreteren

**Comment by kevinkalle** [comment]
Vraag voor morgen.

**Comment by kevinkalle** [comment]
"in de context van het festival" zou eruit kunnen. het gaat er mij vooral om dat het geen random fotoslider is maar dat foto's gekoppeld zijn aan optredens (en logisch terugkomen in het dagboek), dus relevant en contextueel.

**Comment by daniellouwekooijmans** [comment]
Ik zie deze story momenteel meer als een "guiding principle". Ik veronderstel dat als je als gebruiker tijdens een festival foto's hebt gemaakt dat je die in je dagboek zou moeten terug kijken. Wellicht dat we per festival dagboek een content filter kunnen toepassen.
