### ISSUE TITLE
Gebruiker kan contextuele data bekijken op een dashboard

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#91]
Contextuele data, relevant op dat moment. Voor een festival kun je hier bijvoorbeeld advies zien voor festivals of updates dat je je persoonlijk programma kunt aanvullen

### Must have
- Advies voor festivals die de gebruiker misschien interessant vind
- Updates over festival
- Als time-table bekend is: maak je eigen programma aan / rond je programma af

### Must have
- Tijdens festival krijgt user relevante data geserveerd
- Tijdens festival ziet user welke act er straks optreed op basis van haar persoonlijk programma
- Als user geen keuze heeft gemaakt qua persoonlijk programma kunnen we advies bieden voor wat er nu aan komt
- Berichten van festival organisator

### Should have
- Foto maken

### Could have
- Zien waar vrienden nu zijn

**Comment by Martijn-Vermeulen** [comment]
Social media updates van artiesten waar je naar toe gaat of tijdens het optreden waar je op dat moment bent. Die social media updates van de artiesten kunnen ook terug komen in je dagboek.

**Comment by daniellouwekooijmans** [comment]
@Martijn-Vermeulen dit kunnen we evt. pitchen bij Vincent

**Comment by daniellouwekooijmans** [comment]
## Voor festival
Reclame voor aantal festivals, als time-table bekend is: maak je eigen programma aan / rond je programma af
## Tijdens festival
Persoonlijk programma (nu/straks), eventueel nu/straks als je nog niets hebt gekozen, updates van festival organisator, updates van vrienden (waar zijn ze nu), festival kaart met jouw locatie, CTA foto maken/inchecken

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-5](https://cloud.githubusercontent.com/assets/2156865/12547858/fbf32962-c352-11e5-8ec5-8c72ad8563dc.jpg)

**Comment by vincentlindeboom** [comment]
- dashboard tijdens: daar zie je ook je vrienden die gaan (en misschien ge-highlight als er nieuwe vrienden gaan)
- dashboard tijdens: ook foto's van vrienden?
- dashboard tijdens: aangeven hoe lang geleden je een foto hebt gemaakt (dient als incentive om met meer regelmaat foto's te maken) moet overkomen als iets dat in eigen belang is.

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![festival detail tijdens](https://cloud.githubusercontent.com/assets/2156865/12670181/a9ef6aec-c666-11e5-88ce-e29d94c671f8.png)
