### ISSUE TITLE
Gebruiker kan een festival dagboek bijhouden

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#92]
Terugblik op je festival experience, zoveel mogelijk geautomatiseerd met locatie data, foto’s en social media updates. Kan ook door user handmatig aangevuld worden.

### Must have
- Per festival een aparte dagboek
- Elk dagboek kan gedeeld worden
- Dagboek verzamelt welk concert je bezocht hebt, hoe lang 
- Dagboek koppelt automatisch de foto’s aan die je tijdens een concert hebt gemaakt aan het concert (dit moet je wel goedkeuren voordat ze live gaan)
- Dagboek verzamelt tijdens festival social media updates van social media kanalen die je hebt gekoppeld
- Data wordt in de achtergrond verzameld via GPS & Bluetooth
- User kan handmatig inchecken per concert (eventueel met foto)
- User kan handmatig foto’s toevoegen aan een concert
- User kan data verwijderen uit dagboek
- Detail view per entry
- Stats per entry (hoe lang heb je optreden bijgewoond, van hoe laat tot hoe laat, hoeveel mensen waren er, hoe ver van podium was je, info over optreden, optie om een artiest te liken/disliken)
- Overview na afloop van concert met algemene statistieken over het festival

### Taken

**Comment by Martijn-Vermeulen** [comment]
Misschien vet om ook iets met vrienden (vriendendagboek) te doen waarmee je naar het festival bent geweest, aangezien je vaak niet in je eentje naar een festival gaat.

**Comment by daniellouwekooijmans** [comment]
Timeline van concerten, social media updates, foto’s, editen

**Comment by bavaross** [comment]
vind ik een goed idee martijn. uitwerking is hier wel een ding

**Comment by vincentlindeboom** [comment]
Ergens in onze nice-to-haves stond een soort implementatie van "bundle". Samen een foto album samenstellen kan heel goed werken. En is leuk om foto's te zien van je vrienden op festivals. dus mee eens.

**Comment by vincentlindeboom** [comment]
Jullie geven niet het dagboek vorm toch? Dit is dan de soort van customize / settings page voor de ingredienten die het dagboek vormen?

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom klopt. We willen alles in kaart brengen hier maar visueel gaan we het dagboek niet uitwerken.

Vanuit een technisch oogpunt vraag ik me af of het een goed idee is om direct alle dagboek data tijdens een festival te uploaden? Dat zuipt batterij/data toch? Zou het niet handig zijn om op een later moment na het festival het dagboek te kunnen laten aanmaken op basis van verzamelde data (dus ook de inhoud van je foto rol)?

**Comment by vincentlindeboom** [comment]
Niet alles hoeft realtime idd. Ik denk dat we sommige info wel willen gebruiken, bv locatie van jezelf en van vrienden. Maar foto's etc, hoeft idd niet.

**Comment by bavaross** [comment]
vraag is dan wel wat er nog overblijft van een "real-time dagboek". is dan meer een update oid. wat goed genoeg is denk ik.

**Comment by pieterjongsma** [comment]
We zouden inderdaad de foto's pas kunnen uploaden als je op de knop "Maak dagboek" oid drukt. Duurt wel even voor het dagboek er dan is.

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![festival detail na](https://cloud.githubusercontent.com/assets/2156865/12670189/b9c51732-c666-11e5-99b5-c70388f9d4d5.png)
