### ISSUE TITLE
Gebruiker kan festival overzicht bekijken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#93]
Gids om festivals te checken

### Must have
- Aanbevolen festivals op basis van muziek profiel
- User kan door een lijst met festivals kijken
- Per festival een detail view
- User kan zoeken naar festivals
- Niet alle festivals tonen die bestaan, er moet criteria voor komen om te voorkomen dat de user straks door 200 festivals moet scrollen
- Line-up bekijken
- Festival toevoegen aan mijn profiel / aanmelden
- Gebruiker krijgt aanbevelingen op basis van haar muziek profiel

**Comment by daniellouwekooijmans** [comment]
# Festival overzicht
Full-width blokken per festival met foto, logo, datum, locatie
# Festival detail
Festival naam, foto’s, logo, omschrijving, line up CTA, hoeveel mensen aangemeld hebben, timetable bekijken, CTA festival toevoegen, playlist, sharing, persoonlijk programma
# Line-up detail
List view, sort options, search, lange lijst met alle artiesten, artiest detail view, CTA artiest toevoegen
# Artiest detail
Artiest naam, foto, omschrijving, sample muziek, festivals per artiest, CTA toevoegen per festival

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-4](https://cloud.githubusercontent.com/assets/2156865/12547845/eb4929cc-c352-11e5-972f-8c59d5733e4a.jpg)

**Comment by bavaross** [comment]
hier zouden we dus een parallel kunnen maken met de appstore

**Comment by pieterjongsma** [comment]
@daniellouwekooijmans , wat bedoel je met een "full-width blok"?

**Comment by pieterjongsma** [comment]
Ik ben benieuwd naar de invulling van "Niet alle festivals tonen die bestaan, er moet criteria voor komen om te voorkomen dat de user straks door 200 festivals moet scrollen"

**Comment by daniellouwekooijmans** [comment]
![festivals toevoegen](https://cloud.githubusercontent.com/assets/2156865/12670167/9085a5f8-c666-11e5-8ffc-bc595f7dcc92.png)
