### ISSUE TITLE
Gebruiker kan een persooonlijk programma aanmaken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#94]
Feature waarbij user per festival zijn programma kan personaliseren

### Must have
- Line up adviezen gebaseerd op persoonlijk gebruikers profiel
- Gebruiker moet aan kunnen geven welke artiesten zij sowieso wilt zien
- Gebruiker moet ten alle tijden artiesten kunnen toevoegen/verwijderen 
- Gebruiker kan een timetable van zijn gekozen acts zien (vooral handig tijdens festival)
- Gebruiker kan persoonlijk programma delen
- Eventueel playlist van de gekozen acts laten aanmaken op Spotify account van user (vereist Spotify koppeling)

### Flow
- User kiest eerst uit artiesten gesorteerd op Spotify/Lastfm gegevens
- Programma wordt daarop aangemaakt

**Comment by daniellouwekooijmans** [comment]
Overzicht tijden, per tijd gekozen artiest of als er nog geen artiest is gekozen melding en CTA om te kiezen, bij conflict tussen artiesten melding dat je moet kiezen, hulp bij kiezen: bepaalde artiesten naar voorgrond op basis van spotify/lastfm data

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-3](https://cloud.githubusercontent.com/assets/2156865/12547768/701ebabe-c352-11e5-825e-91f43cce27b4.jpg)

**Comment by bavaross** [comment]
Waarom is de playlist "could-have"?

**Comment by vincentlindeboom** [comment]
- spotify playlist is een must have

**Comment by daniellouwekooijmans** [comment]
@bavaross @vincentlindeboom duidelijk 🙂

**Comment by vincentlindeboom** [comment]
=)

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![programma copy](https://cloud.githubusercontent.com/assets/2156865/12670157/74dc791c-c666-11e5-9b70-c0bc26e34823.png)
![programma](https://cloud.githubusercontent.com/assets/2156865/12670156/74da241e-c666-11e5-9cf9-f7522837232b.png)
![suggesties](https://cloud.githubusercontent.com/assets/2156865/12670155/74d3c876-c666-11e5-9da9-2cf86a11d178.png)
![programma share](https://cloud.githubusercontent.com/assets/2156865/12670158/74de48aa-c666-11e5-9ab5-6bfc0491de3c.png)
