### ISSUE TITLE
Gebruiker kan ervaring verrijken met data van vrienden

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#95]
Door Facebook te koppelen kun je informatie krijgen van je vrienden die ook gebruik maken van deze app om je festival ervaring te verrijken.

### Must have
- Facebook koppeling vereist
- Zien naar welke festivals jouw vrienden gaan
- Persoonlijk programma van jouw vrienden bekijken
- Bij festivals zien welke vrienden er heen gaan
- Bij concerten zien welke vrienden er heen gaan
- Dagboek van vrienden bekijken
- Naast vrienden zijn er ook 3FM/BN-ers (gidsen) waarbij dezelfde acties uitgevoerd kunnen worden

### Could have
- Lijst met vrienden
- Zien waar je vrienden zijn tijdens festival

**Comment by Martijn-Vermeulen** [comment]
Als we willen dat je het persoonlijk programma van jouw vrienden kan bekijken, moet er ook een profiel pagina van elke gebruiker komen en opties om vrienden te zoeken om hun profiel te bekijken. Ik denk dat dat het alleen maar ingewikkelder maakt en we ons beter kunnen focussen op het vinden toffe artiesten op een festival, in plaats van er een social network van te maken met vrienden. Wat denken jullie hiervan @daniellouwekooijmans en @vincentlindeboom?

**Comment by vincentlindeboom** [comment]
Eens met Martijn. Je ziet wel dat je vrienden je app populeren. Je ziet ze bij artiesten waar ze naartoe gaan eveneens bij de festivals, maar je hoeft niet hun volledige profiel in te kunnen zien. Misschien in de toekomst.

**Comment by bavaross** [comment]
hier moeten we inderdaad goed overna denken. als gebruiker zou ik wel willen zien / horen wat "gidsen" van plan zijn en gedaan hebben. misschien dat het andersom kan werken; dus vrienden / "gidsen" delen hun programma / playlist / dagboek

**Comment by daniellouwekooijmans** [comment]
Ik denk dat het een toevoeging is dat het algoritme achter festival recommendaties ook de data van vrienden en "gidsen" meeneemt en dat we dit visueel realiseren in een stijl zoals Blende dat ook doet in hun mobiel product, dus met avatars van mensen die deze acts ook willen bijwonen. Hiermee hebben we ons doel behaald (gebruiker helpen nieuwe muziek ontdekken op festivals). Complexer dan dit zou ik op dit moment niet adviseren, zo verliezen we focus.

**Comment by bavaross** [comment]
mooie oplossing. is dit de uitwerking van vooraf, tijdens en achteraf?

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![festival detail tijdens vrienden](https://cloud.githubusercontent.com/assets/2156865/12670138/52e9bdb0-c666-11e5-8727-ae93fd83835c.png)
