### ISSUE TITLE
Gebruiker kan notificaties ontvangen

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#96]
### Should have
- Update wanneer de line-up van een festival bekend is
- Update wanneer iets verandert bij een festival waarvoor gebruiker aangemeld is
- Update wanneer timetable bekend is om eigen programma in elkaar te zetten
- Update dat een optreden op je persoonlijk programma begint in xx minuten
- Berichten van festival organisatoren tijdens een festival

### Could have
- Update om eigen programma in elkaar te zetten wanneer dit nog niet gedaan is en festival is al over een week
- Herinnering om een foto te maken tijdens een optreden

**Comment by daniellouwekooijmans** [comment]
![slack for ios upload-6](https://cloud.githubusercontent.com/assets/2156865/12547898/2ac22c7a-c353-11e5-8a03-8eb3b9a4a9fe.jpg)

**Comment by vincentlindeboom** [comment]
Dit is push toch? Dit moet idd zeker in de app. Nogmaals emails zie ik niet als een in-app onderdeel.

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom yes maar ook in-app moet je oude berichten terug kunnen zien per festival.

**Comment by vincentlindeboom** [comment]
In mijn optiek gaan berichten (push) over wijzigingen in het festival. Mails gaan over algemenere zaken, bv bevestiging van je eerste login, van je aanmelding bij een festival, etc. Die mails hoeven niet in app.

**Comment by pieterjongsma** [comment]
Volgens mij zijn we het eens @vincentlindeboom . Ik wil oude push berichten inderdaad terug kunnen zien @daniellouwekooijmans .
