### ISSUE TITLE
Gebruiker kan berichten ontvangen

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#97]
### Must have
- Gebruiker kan berichten ontvangen en lezen per festival
- Gebruiker kan berichten later teruglezen
- Berichten worden verstuurd door 3FM/Next Empire of door festival organisatoren

**Comment by vincentlindeboom** [comment]
Waarom moet dit (emails) in-app?

**Comment by daniellouwekooijmans** [comment]
Verkeerde interpretatie van onze kant, geen emails dus.

**Comment by pieterjongsma** [comment]
Is dit nu duidelijk? Ik denk dat het hier gaat om de notifications op het "Dashboard", zoals "Storm komt er aan, blijf rustig" of "Nina Simone afgelast". Die willen we wel in de app tonen. Toch @vincentlindeboom ?

**Comment by bavaross** [comment]
eens met Pieter; wel zoveel mogelijk muziek / programma gerelateerd. dat het noodweer wordt communiceren ze op allerlei manieren; voor het dagboek (en zeker voor dashboard tijdens het festival) lijkt me muziek vooral relevant. en dan bij voorkeur alleen de muziek waar ik interesse in heb.

**Comment by vincentlindeboom** [comment]
eens

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![festival nieuws overzicht](https://cloud.githubusercontent.com/assets/2156865/12670126/32808d4c-c666-11e5-8f24-b9af9cfae54d.png)
![festival nieuws detail](https://cloud.githubusercontent.com/assets/2156865/12670125/327065c0-c666-11e5-9c7c-1bcfaec2b1ce.png)
