### ISSUE TITLE
Gebruikers hebben een eigen profiel

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#98]
### Must Have
- Profiel aanmaken & beheren (foto, naam)

### Should have
- Facebook integratie

**Comment by vincentlindeboom** [comment]
Je eigen profiel is naast een foto en naam ook een soort van je muziek-paspoort toch?

**Comment by pieterjongsma** [comment]
@vincentlindeboom Maar kunnen we daar iets van tonen? Is meer onzichtbaar denk ik?

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom @pieterjongsma ons advies is dat het profiel technisch nodig is om namen/avatars bij festivals en concerten te tonen maar er geen user detail view moet zijn die je kan bezoeken, het product is immers geen social network.

**Comment by pieterjongsma** [comment]
Ja, ben ik het mee eens

**Comment by vincentlindeboom** [comment]
Ok mee eens (ik denk dat daar in de toekomst nog wel "muziek" in kan zitten)

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![settings](https://cloud.githubusercontent.com/assets/2156865/12670113/17ca09ba-c666-11e5-925f-f1abc723941b.png)
