### ISSUE TITLE
Gebruiker moet inloggen om de app te gebruiken

### ISSUE THREAD

**Issue by daniellouwekooijmans** [awkward/rewind#99]
App heeft weinig toegevoegde waarde zonder login functie.

### Must have
- Login scherm
- Login met email
- Login met Facebook (voorkeur gaat hier naar uit)

### Should have
- Onboarding

**Comment by Martijn-Vermeulen** [comment]
![img_8456](https://cloud.githubusercontent.com/assets/10687330/12547776/7ad28846-c352-11e5-854d-7329b9955395.JPG)

**Comment by vincentlindeboom** [comment]
Begrijp ik het goed dat we dus wel de app beginnen met login?

**Comment by daniellouwekooijmans** [comment]
@vincentlindeboom ja dat klopt, we hebben geconcludeerd dat een login wel een vereiste is aangezien de focus van de app op de voorkeuren en beleving van het individu is.

**Comment by vincentlindeboom** [comment]
ok, langs dat pad geloof ik hem wel. let's do it. @pieterjongsma mee eens?

**Comment by pieterjongsma** [comment]
Hmm, vind ik tricky. Ik ben niet helemaal overtuigd door bovenstaand argument, omdat ik denk dat we het registreren van voorkeuren en individualiseren ook kunnen bereiken zonder een gebruiker (meteen) in te laten loggen. Volgens mij winnen we door gebruikers eerder met email in te laten loggen zelfs niets. Daartegenover denk ik dat veel zaken wel eenvoudiger worden (design & implementatie) door dit wel af te dwingen en gezien de beperkte tijd kan ik me daar wel in vinden. Akkoord dus.

**Comment by daniellouwekooijmans** [comment]
#### Wireframe

![login1](https://cloud.githubusercontent.com/assets/2156865/12670092/fe21ec26-c665-11e5-9827-e93a347b7a36.png)
![login2](https://cloud.githubusercontent.com/assets/2156865/12670093/fe233694-c665-11e5-9034-610eca79a537.png)
![login3](https://cloud.githubusercontent.com/assets/2156865/12670097/fe299cb4-c665-11e5-8c79-17fe1fe522dc.png)
![login4](https://cloud.githubusercontent.com/assets/2156865/12670096/fe28474c-c665-11e5-97f3-0299e0f3a394.png)
![login5](https://cloud.githubusercontent.com/assets/2156865/12670095/fe26bf8a-c665-11e5-92dc-1a1ddfb3ca73.png)
![login6](https://cloud.githubusercontent.com/assets/2156865/12670094/fe265496-c665-11e5-8cf3-d5b63dc6b2cb.png)
![login7](https://cloud.githubusercontent.com/assets/2156865/12670098/fe316994-c665-11e5-8382-78ad806b8140.png)
![login9](https://cloud.githubusercontent.com/assets/2156865/12670099/fe3753b8-c665-11e5-8e6b-be42b913089b.png)
